version: "3"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "passw"
      POSTGRES_DB: "mydb"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "usr"
      PGADMIN_DEFAULT_PASSWORD: "passw"
